# Generated by Django 4.1 on 2022-09-01 20:16

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Избранное',
            },
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ингредиент')),
                ('amount', models.IntegerField(verbose_name='Колличество')),
                ('measurement_unit', models.CharField(choices=[('ч. л.', 'ч. л'), ('ст. л.', 'ст. л.'), ('г', 'г'), ('стакан', 'стакан'), ('по вкусу', 'по вкусу'), ('шт', 'шт'), ('капля', 'капля'), ('кг', 'кг'), ('мл', 'мл'), ('щепотка', 'щепотка')], max_length=200, verbose_name='Еденица измерения')),
            ],
            options={
                'verbose_name_plural': 'Ингредиенты',
            },
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название рецепта')),
                ('image', models.ImageField(null=True, upload_to='.../')),
                ('description', models.TextField(verbose_name='Описание')),
                ('cooking_time', models.IntegerField(verbose_name='Время приготовления. мин')),
            ],
            options={
                'verbose_name_plural': 'Рецепты',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Тег')),
                ('color', colorfield.fields.ColorField(choices=[('#FFFFFF', 'белый'), ('#000000', 'черный'), ('ff0000', 'красный'), ('ff00fb', 'розовый'), ('4000ff', 'синий'), ('00ffee', 'голубой'), ('00ff00', 'зелёный'), ('e6ff00', 'желтый'), ('ff6f00', 'оранжевый')], default='#FFFFFF', image_field=None, max_length=18, samples=None)),
                ('slug', models.SlugField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Тэги',
            },
        ),
    ]
