# Generated by Django 4.1 on 2022-08-23 19:12

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ингредиент')),
                ('amount', models.IntegerField()),
                ('measurement_unit', models.CharField(choices=[('ч. л.', '1'), ('ст. л.', '2'), ('г', '3'), ('стакан', '4'), ('по вкусу', '5'), ('шт', '6'), ('капля', '7'), ('кг', '8'), ('мл', '9'), ('щепотка', '10')], max_length=200, verbose_name='Еденица измерения')),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название рецепта')),
                ('image', models.ImageField(blank=True, null=True, upload_to='.../')),
                ('description', models.TextField()),
                ('cooking_time', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Рецепты',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Тег')),
                ('color', colorfield.fields.ColorField(choices=[('#FFFFFF', 'белый'), ('#000000', 'черный'), ('ff0000', 'красный'), ('ff00fb', 'розовый'), ('4000ff', 'синий'), ('00ffee', 'голубой'), ('00ff00', 'зелёный'), ('e6ff00', 'желтый'), ('ff6f00', 'оранжевый')], default='#FFFFFF', image_field=None, max_length=18, samples=None)),
                ('slug', models.SlugField(max_length=20, unique=True)),
            ],
        ),
    ]
