# Generated by Django 4.1 on 2022-09-02 08:06

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=[('#FFFFFF', 'белый'), ('#000000', 'черный'), ('ff0000', 'красный'), ('ff00fb', 'розовый'), ('4000ff', 'синий'), ('00ffee', 'голубой'), ('00ff00', 'зелёный'), ('e6ff00', 'желтый'), ('ff6f00', 'оранжевый')]),
        ),
    ]
