# Generated by Django 4.1 on 2022-09-02 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_description_recipes_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipes',
            old_name='title',
            new_name='name',
        ),
    ]
