# Generated by Django 4.1 on 2022-09-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_recipes_cooking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='cooking_time',
            field=models.IntegerField(default=1, verbose_name='Время приготовления. мин'),
            preserve_default=False,
        ),
    ]
