# Generated by Django 4.1 on 2022-09-03 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_alter_recipes_cooking_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoping_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Shoping_cart', to='api.recipes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Shoping_cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='Shoping_cart',
            constraint=models.UniqueConstraint(fields=('recipes', 'user'), name='unique_chopping_cart_recipes'),
        ),
    ]
