# Generated by Django 4.1 on 2022-09-05 10:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_shoping_cart_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='Shoping_cart',
            options={'verbose_name_plural': 'Карзина покупок'},
        ),
        migrations.RenameField(
            model_name='tags',
            old_name='title',
            new_name='name',
        ),
        migrations.CreateModel(
            name='Amount_of_ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Меньше 1 быть не может')])),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.ingredients')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.recipes')),
            ],
        ),
        migrations.AddConstraint(
            model_name='amount_of_ingredients',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='unique_recipe_ingredient'),
        ),
    ]
