# Generated by Django 4.1 on 2022-09-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_shopping_cart_options_rename_title_tags_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amount_of_ingredients',
            options={'verbose_name_plural': 'Общее колличество ингредиентов'},
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='measurement_unit',
            field=models.CharField(max_length=200, verbose_name='Еденица измерения'),
        ),
    ]
