# Generated by Django 4.1 on 2022-09-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_amount_of_ingredients_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='measurement_unit',
            field=models.CharField(choices=[('ч. л.', 'ч. л'), ('ст. л.', 'ст. л.'), ('г', 'г'), ('стакан', 'стакан'), ('по вкусу', 'по вкусу'), ('шт', 'шт'), ('капля', 'капля'), ('кг', 'кг'), ('мл', 'мл'), ('щепотка', 'щепотка')], max_length=200, verbose_name='Еденица измерения'),
        ),
    ]
